window.AI_KUAIDA_MODEL = {
  navigation: [
    {
      id: "library",
      label: "Knowledge & Library Hub",
      defaultView: "library",
      views: [
        { id: "library", label: "Search" },
        { id: "smeReviewed", label: "Approved Answers" },
        { id: "goldenSource", label: "Sources" },
        { id: "completedLibrary", label: "Historical Questionnaires" },
        { id: "contentGovernance", label: "Content Governance" },
      ],
    },
    {
      id: "workspace",
      label: "Recommendation Engines",
      defaultView: "workspaceDashboard",
      views: [
        { id: "workspaceDashboard", label: "All Questionnaires" },
        { id: "myQuestionnaires", label: "My Questionnaires" },
        { id: "uploadQuestionnaire", label: "Create / Upload" },
        { id: "workbench", label: "Recommendation Workbench", hidden: true },
      ],
    },
    {
      id: "settings",
      label: "Settings / Admin",
      defaultView: "governance",
      views: [
        { id: "governance", label: "Hashtag Dictionary" },
        { id: "dictionaries", label: "Dropdown Dictionaries" },
        { id: "statusConfig", label: "Status Configuration" },
        { id: "workflowRules", label: "Workflow Rules" },
        { id: "qualityRules", label: "Quality & Risk Rules" },
        { id: "notifications", label: "Email Automation" },
        { id: "roles", label: "Access Model" },
        { id: "model", label: "Data Model" },
      ],
    },
  ],
  entities: [
    {
      name: "Questionnaire",
      purpose: "A client-uploaded RFP/DDQ/AFME questionnaire, acting as the project-level object in the Recommendation Engines.",
      fields: [
        "questionnaire_id",
        "name",
        "client_or_project",
        "type",
        "market",
        "service_scope",
        "uploaded_at",
        "due_date",
        "owner",
        "status",
        "completion_rate",
        "average_confidence",
        "risk_level",
        "source_file",
        "final_export_files",
      ],
    },
    {
      name: "Question",
      purpose: "A single question extracted from a client questionnaire, the smallest work unit for matching, review and writeback.",
      fields: [
        "question_id",
        "questionnaire_id",
        "original_question",
        "detected_topic",
        "detected_subtopic",
        "question_type",
        "required_flag",
        "source_sheet",
        "row",
        "column",
        "word_paragraph",
        "auto_hashtags",
        "best_match_source",
        "suggested_answer_id",
        "confidence_score",
        "risk_level",
        "owner",
        "sme",
        "review_status",
        "review_history",
      ],
    },
    {
      name: "KnowledgeItem",
      purpose: "A reusable standard answer or knowledge fragment in the Knowledge Hub.",
      fields: [
        "knowledge_item_id",
        "topic",
        "subtopic",
        "standard_question",
        "standard_answer",
        "source_type",
        "source_reference_id",
        "owner",
        "sme_reviewer",
        "status",
        "confidence_score",
        "last_reviewed_date",
        "next_review_date",
        "hashtags",
        "usage_count",
        "last_used_in",
        "version",
        "audit_trail",
      ],
    },
    {
      name: "Source",
      purpose: "A Golden Source, internal document, historical questionnaire or evidence attachment.",
      fields: [
        "source_id",
        "source_title",
        "source_type",
        "source_url_or_file",
        "source_owner",
        "published_date",
        "captured_date",
        "validity_status",
        "related_topics",
        "extracted_knowledge_items",
        "confidence_level",
        "review_requirement",
        "hashtags",
      ],
    },
    {
      name: "ReviewRecord",
      purpose: "Review and sign-off records from SME, Business, Compliance, Legal and InfoSec.",
      fields: [
        "review_id",
        "target_type",
        "target_id",
        "reviewer",
        "reviewer_role",
        "action",
        "comment",
        "status_before",
        "status_after",
        "created_at",
      ],
    },
    {
      name: "Hashtag",
      purpose: "A tag node in the background relationship engine, linking questions, knowledge, sources, historical answers and review workflows.",
      fields: [
        "hashtag_id",
        "name",
        "category",
        "risk_weight",
        "workflow_trigger",
        "description",
        "merged_into",
        "usage_count",
      ],
    },
    {
      name: "FinalAnswer",
      purpose: "The final answer written back into the client template or submission version.",
      fields: [
        "final_answer_id",
        "question_id",
        "answer_text",
        "source_evidence_ids",
        "knowledge_item_ids",
        "approval_record_ids",
        "signoff_status",
        "export_target",
        "exported_at",
      ],
    },
    {
      name: "WorkflowTemplate",
      purpose: "A reusable review workflow template supporting standard and custom workflows.",
      fields: [
        "template_id",
        "template_name",
        "description",
        "mode",
        "number_of_stages",
        "default_roles",
        "applies_to",
        "mandatory_stages",
        "created_by",
        "last_used",
        "status",
      ],
    },
    {
      name: "WorkflowStage",
      purpose: "A configurable stage within a Workflow Template, driving dynamic dashboards, buttons and export gates.",
      fields: [
        "stage_id",
        "stage_name",
        "stage_type",
        "owner_type",
        "default_owner",
        "applies_to",
        "mandatory_flag",
        "allow_edit_answer",
        "allow_comment_only",
        "allow_reassign",
        "requires_acceptance",
        "due_date_rule",
        "completion_rule",
        "blocking_rule",
        "notification_rule",
        "escalation_rule",
        "signoff_required",
        "sort_order",
      ],
    },
    {
      name: "AssignmentTask",
      purpose: "The unified task object for three-level questionnaire, section and question assignments.",
      fields: [
        "assignment_id",
        "scope_type",
        "scope_id",
        "workflow_stage_id",
        "current_owner",
        "review_chain",
        "risk_level",
        "confidence_score",
        "source_status",
        "due_date",
        "assignment_status",
        "reassign_count",
        "blocking_reason",
        "last_action",
        "audit_trail",
      ],
    },
    {
      name: "Reassignment",
      purpose: "Records task re-assignment, acceptance, refusal, PM intervention and escalation rules.",
      fields: [
        "reassignment_id",
        "assignment_id",
        "original_owner",
        "reassigned_to",
        "scope",
        "reason",
        "suggested_due_date",
        "keep_original_owner_as_watcher",
        "notify_project_owner",
        "requires_acceptance",
        "acceptance_status",
        "pm_action",
      ],
    },
  ],
  relationships: [
    "Questionnaire 1:N Question",
    "Question N:N Hashtag",
    "Question N:N KnowledgeItem",
    "KnowledgeItem N:1 Source",
    "KnowledgeItem 1:N ReviewRecord",
    "Question N:N Historical Question",
    "FinalAnswer N:N Source Evidence",
    "FinalAnswer 1:N ApprovalRecord",
    "WorkflowTemplate 1:N WorkflowStage",
    "Questionnaire N:1 WorkflowTemplate",
    "WorkflowStage 1:N AssignmentTask",
    "AssignmentTask N:1 Question / Section / Questionnaire",
    "AssignmentTask 1:N Reassignment",
  ],
  statuses: {
    questionnaire: ["Parsing", "Drafting", "Stakeholders Reviewing", "Stakeholders Reviewed", "Completion", "Withdrawn"],
    question: ["Not Started", "Auto Matched", "Needs Review", "In SME Review", "SME Approved", "Business Approved", "Compliance Approved", "Final Approved", "Rejected", "Blocked"],
    knowledgeItem: ["Draft", "In Review", "Approved", "Needs Review", "Expired", "Archived"],
    source: ["Active", "Possibly Outdated", "Expired", "Replaced", "Unverified"],
  },
};

