window.AI_KUAIDA_WORKFLOW = {
  defaultMode: "standard",
  selectedTemplateId: "standard-four-step",
  stageTypes: {
    Draft: ["Generate Draft", "Edit Answer", "Attach Source", "Mark as Draft Done", "Submit to Next Stage"],
    Review: ["Start Review", "Edit Answer", "Add Comment", "Request Clarification", "Approve Review", "Reject / Return", "Re-assign Reviewer", "Mark as Blocked"],
    Approval: ["Approve", "Reject", "Request Change", "Escalate"],
    Signoff: ["Approve", "Reject", "Request Change", "Escalate", "Sign Off"],
    Formatting: ["Apply House Style", "Check Consistency", "Run Final QA", "Mark Final Ready"],
    "Export Check": ["Run Export Check", "Preview Export", "Export Word", "Export Excel", "Generate Internal Audit Version"],
  },
  stageLibrary: [
    {
      id: "first-draft",
      name: "First Draft",
      type: "Draft",
      role: "DDQ/RFP First Drafter",
      ownerType: "Role-based",
      defaultOwner: "Drafter Pool",
      appliesTo: "All Questions",
      mandatory: true,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 10 days",
      completionRule: "Draft answer exists and source attached",
      blockingRule: "Blocks next mandatory stage",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to Questionnaire Owner after 1 day overdue",
      signoffRequired: false,
    },
    {
      id: "sme-review",
      name: "SME Review",
      type: "Review",
      role: "SME Reviewer",
      ownerType: "Role-based",
      defaultOwner: "Section SME",
      appliesTo: "Selected Sections / High Risk Only",
      mandatory: true,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 7 days",
      completionRule: "SME approves or returns with comment",
      blockingRule: "Blocks export for mandatory scope",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to PM after 2 days overdue",
      signoffRequired: false,
    },
    {
      id: "business-control",
      name: "Business Control",
      type: "Approval",
      role: "Deal Owner / Client Management Team",
      ownerType: "Team",
      defaultOwner: "Client Management Team",
      appliesTo: "All Questions",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 4 days",
      completionRule: "Business control approved",
      blockingRule: "Blocks final consolidation",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Business Sponsor",
      signoffRequired: false,
    },
    {
      id: "final-consolidation",
      name: "Final Consolidation",
      type: "Formatting",
      role: "Final Drafter",
      ownerType: "Individual",
      defaultOwner: "Final Drafter",
      appliesTo: "All Questions",
      mandatory: true,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: false,
      requiresAcceptance: false,
      dueDateRule: "Questionnaire due date - 2 days",
      completionRule: "All answers formatted and marked final ready",
      blockingRule: "Blocks export if incomplete",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Questionnaire Owner",
      signoffRequired: false,
    },
    {
      id: "compliance-review",
      name: "Compliance Review",
      type: "Review",
      role: "Compliance",
      ownerType: "Team",
      defaultOwner: "Compliance Team",
      appliesTo: "Regulatory Sensitive / High Risk Only",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 6 days",
      completionRule: "Compliance approval recorded",
      blockingRule: "Blocks export for regulatory sensitive items",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to Compliance Lead",
      signoffRequired: false,
    },
    {
      id: "legal-review",
      name: "Legal Review",
      type: "Review",
      role: "Legal",
      ownerType: "Team",
      defaultOwner: "Legal Team",
      appliesTo: "Client Commitment / Legal Sensitive",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 5 days",
      completionRule: "Legal approval recorded",
      blockingRule: "Blocks signoff",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to Legal Lead",
      signoffRequired: false,
    },
    {
      id: "regional-review",
      name: "Regional Review",
      type: "Review",
      role: "Regional Reviewer",
      ownerType: "Role-based",
      defaultOwner: "Regional SME",
      appliesTo: "Selected Sections",
      mandatory: false,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 5 days",
      completionRule: "Regional comment or approval recorded",
      blockingRule: "Optional unless marked mandatory",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Regional Lead",
      signoffRequired: false,
    },
    {
      id: "product-owner-review",
      name: "Product Owner Review",
      type: "Review",
      role: "Product Owner",
      ownerType: "Role-based",
      defaultOwner: "Product Owner",
      appliesTo: "Selected Sections",
      mandatory: false,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 5 days",
      completionRule: "Product owner approved",
      blockingRule: "Blocks selected scope only",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Product Lead",
      signoffRequired: false,
    },
    {
      id: "risk-review",
      name: "Risk Review",
      type: "Review",
      role: "Risk Control",
      ownerType: "Team",
      defaultOwner: "Risk Control Team",
      appliesTo: "High Risk Only",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 6 days",
      completionRule: "Risk control approved",
      blockingRule: "Blocks export for high risk scope",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to Risk Lead",
      signoffRequired: false,
    },
    {
      id: "data-owner-review",
      name: "Data Owner Review",
      type: "Review",
      role: "Data Owner",
      ownerType: "Role-based",
      defaultOwner: "Data Owner",
      appliesTo: "Data Protection / Systems Sections",
      mandatory: false,
      allowEditAnswer: true,
      allowCommentOnly: false,
      allowReassign: true,
      requiresAcceptance: true,
      dueDateRule: "Questionnaire due date - 5 days",
      completionRule: "Data owner approved",
      blockingRule: "Blocks selected scope only",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Data Governance Lead",
      signoffRequired: false,
    },
    {
      id: "final-signoff",
      name: "Final Signoff",
      type: "Signoff",
      role: "Senior Approver",
      ownerType: "Individual",
      defaultOwner: "Senior Approver",
      appliesTo: "All Questions",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: false,
      requiresAcceptance: false,
      dueDateRule: "Questionnaire due date - 1 day",
      completionRule: "Formal signoff recorded",
      blockingRule: "Blocks export",
      notificationRule: "Email + system reminder",
      escalationRule: "Escalate to Business Sponsor",
      signoffRequired: true,
    },
    {
      id: "export-check",
      name: "Export Check",
      type: "Export Check",
      role: "Final Drafter / PM",
      ownerType: "Role-based",
      defaultOwner: "RFP PM",
      appliesTo: "All Questions",
      mandatory: true,
      allowEditAnswer: false,
      allowCommentOnly: true,
      allowReassign: false,
      requiresAcceptance: false,
      dueDateRule: "Questionnaire due date",
      completionRule: "Export readiness checks passed",
      blockingRule: "Blocks client package generation",
      notificationRule: "System reminder",
      escalationRule: "Escalate to Questionnaire Owner",
      signoffRequired: false,
    },
  ],
  templates: [
    {
      id: "sme-only",
      name: "SME Review Only",
      description: "Suitable for simple DDQs with existing standard answers and lower risk.",
      mode: "custom",
      appliesTo: "Low risk DDQ / simple questionnaire",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-06-07",
      stages: ["sme-review"],
    },
    {
      id: "simple-three-step",
      name: "Simple 3-Step Review",
      description: "First Draft → SME Review → Final Consolidation → Export.",
      mode: "custom",
      appliesTo: "Medium complexity DDQ",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-06-03",
      stages: ["first-draft", "sme-review", "final-consolidation"],
    },
    {
      id: "standard-four-step",
      name: "Standard 4-Step RFP/DDQ",
      description: "Default standard workflow for formal RFPs and DDQs.",
      mode: "standard",
      appliesTo: "Formal RFP / DDQ",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-06-07",
      stages: ["first-draft", "sme-review", "business-control", "final-consolidation"],
    },
    {
      id: "high-risk-regulatory",
      name: "High Risk Regulatory Workflow",
      description: "Adds Compliance, Legal, Risk and Final Signoff for regulatory, legal, information-security and client-commitment questionnaires.",
      mode: "custom",
      appliesTo: "High risk / regulatory sensitive questionnaire",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-06-05",
      stages: ["first-draft", "sme-review", "compliance-review", "legal-review", "risk-review", "business-control", "final-signoff", "final-consolidation"],
    },
    {
      id: "client-commitment",
      name: "Client Commitment Workflow",
      description: "Emphasises commercial commitments, legal wording and client-message control.",
      mode: "custom",
      appliesTo: "Client commitment / commercial sensitive RFP",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-05-28",
      stages: ["first-draft", "sme-review", "legal-review", "business-control", "final-signoff", "final-consolidation"],
    },
    {
      id: "infosec-ddq",
      name: "Information Security DDQ Workflow",
      description: "Emphasises data ownership, information security, compliance and final sign-off.",
      mode: "custom",
      appliesTo: "CAIQ / SIG / InfoSec DDQ",
      createdBy: "System",
      status: "Active",
      lastUsed: "2026-05-21",
      stages: ["first-draft", "data-owner-review", "sme-review", "compliance-review", "final-signoff"],
    },
  ],
  reassignmentReasons: [
    "Not my subject matter",
    "Need specialist input",
    "Regional expertise required",
    "Product-specific expertise required",
    "Workload capacity issue",
    "Compliance input required",
    "Data owner input required",
    "Other",
  ],
  exportReadinessRules: [
    "All mandatory stages completed",
    "High risk questions completed required reviews",
    "Re-assigned tasks accepted and completed",
    "Blocked / overdue tasks resolved",
    "All answers have approved or accepted sources",
    "Final required questions reached Final Ready",
    "Required signoff completed",
    "No Draft / Expired / Missing Source content in client version",
  ],
};
